---
name: Backend Coding Standard
on: [ push, pull_request_target ]
jobs:
    approve: # First step
        runs-on: ubuntu-latest
        steps:
        - name: Approve
          run: echo For security reasons, all pull requests need to be approved first before running any automated CI.

    backend-lint:
        runs-on: ubuntu-latest
        needs: [ approve ] # Require the first step to finish
        environment:
           name: Approve PR # Our dummy environmen
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: shivammathur/setup-php@v2
              with:
                php-version: '7.3'

            - name: Add composer repositories
              env:
                USERNAME: ${{ secrets.COMPOSER_MAGENTO_USERNAME }}
                PASSWORD: ${{ secrets.COMPOSER_MAGENTO_PASSWORD }}
              run: composer config repositories.magento composer https://$USERNAME:$PASSWORD@repo.magento.com/

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Run tests
              run: composer run-script test
