---
name: Backend Coding Standard (PR)
on:
    pull_request_target:
        types: [labeled]
jobs:
    backend-lint:
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'safe to test')
        steps:
            - name: Fork Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: shivammathur/setup-php@v2
              with:
                php-version: '7.3'

            - name: Add composer repositories
              env:
                USERNAME: ${{ secrets.COMPOSER_MAGENTO_USERNAME }}
                PASSWORD: ${{ secrets.COMPOSER_MAGENTO_PASSWORD }}
              run: composer config repositories.magento composer https://$USERNAME:$PASSWORD@repo.magento.com/

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Run tests
              run: composer run-script test
