name: Label PR
on:
    pull_request_target:
jobs:
    label_issues:
        runs-on: ubuntu-latest
        steps:
            - name: Label PR
              uses: andymckay/labeler@master
              with:
                  remove-labels: "safe to test"
                  add-labels: "check is safe to test"
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

