name: Label PR
on:
    pull_request_target:
jobs:
    label_issues:
        runs-on: ubuntu-latest
        if: github.event.pull_request.head.repo.full_name != github.repository && github.actor != 'dependabot[bot]'
        steps:
            - name: Label PR
              uses: andymckay/labeler@master
              with:
                  remove-labels: "safe to test"
                  add-labels: "check is safe to test"
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

