---
name: Backend Coding Standard
on: [ push, pull_request_target ]
jobs:
    backend-lint:
        name: Backend Coding Standard Step
        runs-on: ubuntu-latest
        steps:
            - run: env
